name: Continuous Integration

on:
  push:
    paths:
      - src/**
      - build.gradle
      - gradle.properties

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set build number
        run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts for ${{ github.sha }}
          path: build/libs/